version: '3.8'

services:
  executive-task-bot:
    build: .
    container_name: executive_task_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./firebase_credentials.json:/app/firebase_credentials.json:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
